# Generated by Django 4.0.2 on 2022-06-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contact_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.CharField(default=20, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default=20, max_length=202),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=20, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=20, max_length=20),
        ),
    ]
