# Generated by Django 4.0.2 on 2022-06-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(default=20, max_length=20),
        ),
        migrations.AlterField(
            model_name='services',
            name='Select',
            field=models.CharField(max_length=250),
        ),
    ]
