# Generated by Django 3.0.14 on 2022-06-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20220611_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='nologin',
        ),
    ]
