# Generated by Django 3.0.14 on 2022-06-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_login_nologin'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=20, max_length=20)),
                ('lname', models.CharField(default=20, max_length=20)),
                ('username', models.CharField(default=20, max_length=20)),
                ('city', models.CharField(default=20, max_length=100)),
                ('state', models.CharField(default=20, max_length=50)),
                ('zip', models.CharField(default=20, max_length=50)),
                ('comments', models.CharField(default=20, max_length=100)),
                ('commenttime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
