# Generated by Django 3.0.14 on 2022-06-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_comments_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=20, max_length=20)),
                ('item', models.CharField(default=20, max_length=20)),
                ('noofitem', models.IntegerField(default=0)),
                ('itemrate', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='services',
        ),
    ]
